"""Narrative intelligence report generator."""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

from narrativealpha.models import Narrative


@dataclass
class NarrativeReport:
    """Generated narrative intelligence report."""

    generated_at: datetime
    period_start: datetime
    period_end: datetime

    # Summary stats
    total_narratives: int
    active_narratives: int
    emerging_narratives: int
    declining_narratives: int

    # Top narratives
    top_narratives: list[dict] = field(default_factory=list)
    emerging: list[dict] = field(default_factory=list)
    declining: list[dict] = field(default_factory=list)

    # Sentiment breakdown
    sentiment_distribution: dict = field(default_factory=dict)

    # Content samples
    recent_posts: list[dict] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Generate markdown report."""
        lines = [
            f"# Narrative Intelligence Report",
            f"",
            f"**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Period:** {self.period_start.strftime('%Y-%m-%d')} to {self.period_end.strftime('%Y-%m-%d')}",
            f"",
            f"---",
            f"",
            f"## Executive Summary",
            f"",
            f"- **Total Narratives Tracked:** {self.total_narratives}",
            f"- **Active Narratives:** {self.active_narratives}",
            f"- **Emerging (new/rapidly growing):** {self.emerging_narratives}",
            f"- **Declining (losing momentum):** {self.declining_narratives}",
            f"",
        ]

        if self.top_narratives:
            lines.extend([
                f"## Top Narratives by Score",
                f"",
                f"| Rank | Narrative | Score | Sentiment | Velocity |",
                f"|------|-----------|-------|-----------|----------|",
            ])
            for i, n in enumerate(self.top_narratives[:10], 1):
                sentiment_emoji = "🟢" if n.get("sentiment_score", 0) > 0.1 else "🔴" if n.get("sentiment_score", 0) < -0.1 else "⚪"
                lines.append(
                    f"| {i} | **{n['name']}** | {n.get('overall_score', 0):.2f} | {sentiment_emoji} {n.get('sentiment_score', 0):.2f} | {n.get('velocity_score', 0):.2f} |"
                )
            lines.append("")

        if self.emerging:
            lines.extend([
                f"## 🚀 Emerging Narratives",
                f"",
                f"These narratives are gaining momentum rapidly:",
                f"",
            ])
            for n in self.emerging[:5]:
                lines.append(f"- **{n['name']}** — Velocity: {n.get('velocity_score', 0):.2f}, Score: {n.get('overall_score', 0):.2f}")
            lines.append("")

        if self.declining:
            lines.extend([
                f"## 📉 Declining Narratives",
                f"",
                f"These narratives are losing momentum:",
                f"",
            ])
            for n in self.declining[:5]:
                lines.append(f"- **{n['name']}** — Last seen: {n.get('last_seen', 'unknown')}")
            lines.append("")

        if self.sentiment_distribution:
            pos = self.sentiment_distribution.get("positive", 0)
            neg = self.sentiment_distribution.get("negative", 0)
            neu = self.sentiment_distribution.get("neutral", 0)
            total = pos + neg + neu
            if total > 0:
                lines.extend([
                    f"## Sentiment Distribution",
                    f"",
                    f"- 🟢 Positive: {pos} ({100*pos/total:.1f}%)",
                    f"- 🔴 Negative: {neg} ({100*neg/total:.1f}%)",
                    f"- ⚪ Neutral: {neu} ({100*neu/total:.1f}%)",
                    f"",
                ])

        lines.extend([
            f"---",
            f"",
            f"*Report generated by NarrativeAlpha — AI-powered narrative intelligence*",
        ])

        return "\n".join(lines)

    def to_json(self) -> dict:
        """Generate JSON report."""
        return {
            "generated_at": self.generated_at.isoformat(),
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "summary": {
                "total_narratives": self.total_narratives,
                "active_narratives": self.active_narratives,
                "emerging_narratives": self.emerging_narratives,
                "declining_narratives": self.declining_narratives,
            },
            "top_narratives": self.top_narratives,
            "emerging": self.emerging,
            "declining": self.declining,
            "sentiment_distribution": self.sentiment_distribution,
        }


class ReportGenerator:
    """Generate narrative intelligence reports from stored data."""

    def __init__(self, db_path: str | None = None):
        self.db_path = Path(db_path or "data/narrativealpha.db")

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self.db_path)

    def generate_report(
        self,
        hours: int = 24,
        min_score: float = 0.0,
    ) -> NarrativeReport:
        """Generate a narrative intelligence report.

        Args:
            hours: Lookback period in hours (default: 24)
            min_score: Minimum overall score to include (default: 0)

        Returns:
            NarrativeReport with intelligence data
        """
        now = datetime.utcnow()
        period_start = now - timedelta(hours=hours)

        with self._connect() as conn:
            # Get all narratives
            narratives = self._fetch_narratives(conn, min_score)

            # Get active narratives
            active = [n for n in narratives if n.get("is_active", 0) == 1]

            # Get emerging (recently created, high velocity)
            emerging = self._fetch_emerging(conn, period_start)

            # Get declining (stale narratives)
            declining = self._fetch_declining(conn, period_start)

            # Calculate sentiment distribution
            sentiment_dist = self._calculate_sentiment_distribution(active)

        # Build report
        report = NarrativeReport(
            generated_at=now,
            period_start=period_start,
            period_end=now,
            total_narratives=len(narratives),
            active_narratives=len(active),
            emerging_narratives=len(emerging),
            declining_narratives=len(declining),
            top_narratives=self._format_narratives(sorted(active, key=lambda x: x.get("overall_score", 0), reverse=True)[:10]),
            emerging=self._format_narratives(emerging[:5]),
            declining=self._format_narratives(declining[:5]),
            sentiment_distribution=sentiment_dist,
        )

        return report

    def _fetch_narratives(self, conn: sqlite3.Connection, min_score: float) -> list[dict]:
        cursor = conn.execute(
            """
            SELECT
                id, name, description,
                first_seen, last_seen,
                cashtags, keywords,
                sentiment_score, velocity_score, saturation_score, overall_score,
                is_active, confidence
            FROM narratives
            WHERE overall_score >= ?
            ORDER BY overall_score DESC
            """,
            (min_score,),
        )
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    def _fetch_emerging(self, conn: sqlite3.Connection, since: datetime) -> list[dict]:
        """Fetch narratives that emerged in the given period."""
        cursor = conn.execute(
            """
            SELECT
                id, name, description,
                first_seen, last_seen,
                sentiment_score, velocity_score, saturation_score, overall_score,
                is_active, confidence
            FROM narratives
            WHERE first_seen >= ?
            AND velocity_score > 0.5
            ORDER BY velocity_score DESC
            LIMIT 10
            """,
            (since.isoformat(),),
        )
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    def _fetch_declining(self, conn: sqlite3.Connection, since: datetime) -> list[dict]:
        """Fetch narratives that haven't been updated recently."""
        cursor = conn.execute(
            """
            SELECT
                id, name, description,
                first_seen, last_seen,
                sentiment_score, velocity_score, saturation_score, overall_score,
                is_active, confidence
            FROM narratives
            WHERE last_seen < ?
            AND is_active = 1
            ORDER BY last_seen ASC
            LIMIT 10
            """,
            (since.isoformat(),),
        )
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]

    def _calculate_sentiment_distribution(self, narratives: list[dict]) -> dict:
        """Calculate sentiment distribution across narratives."""
        positive = sum(1 for n in narratives if n.get("sentiment_score", 0) > 0.1)
        negative = sum(1 for n in narratives if n.get("sentiment_score", 0) < -0.1)
        neutral = len(narratives) - positive - negative

        return {
            "positive": positive,
            "negative": negative,
            "neutral": neutral,
        }

    def _format_narratives(self, narratives: list[dict]) -> list[dict]:
        """Format narratives for report output."""
        formatted = []
        for n in narratives:
            formatted.append({
                "id": n.get("id"),
                "name": n.get("name"),
                "description": n.get("description", "")[:200],
                "sentiment_score": n.get("sentiment_score", 0),
                "velocity_score": n.get("velocity_score", 0),
                "saturation_score": n.get("saturation_score", 0),
                "overall_score": n.get("overall_score", 0),
                "confidence": n.get("confidence", 0),
                "first_seen": n.get("first_seen"),
                "last_seen": n.get("last_seen"),
                "is_active": bool(n.get("is_active", 0)),
                "cashtags": self._parse_json_field(n.get("cashtags")),
                "keywords": self._parse_json_field(n.get("keywords")),
            })
        return formatted

    def _parse_json_field(self, field: str | None) -> list[str]:
        """Parse JSON string field."""
        if not field:
            return []
        try:
            import json
            return json.loads(field)
        except (json.JSONDecodeError, TypeError):
            return []
